### ISSUE TITLE
Script d'installation manquant

### ISSUE THREAD

**Issue by ohemelaar** [renaudzigmann/console-seolan#1]
Bonjour,

Selon la documentation, l'installation devrait se faire en lançant le script se trouvant sous `scripts/install/install.php`. Je ne trouve pas ce script dans le repo, a-t-il été déplacé/renommé ?

Merci

**Comment by renaudzigmann** [comment]
Je corrige : j'ai réussi à transférer

**Comment by xsalto-richard** [comment]
Bonjour,
je vais reprendre la documentation et le script de vérification des composants. 
Vous étiez sur quel ubuntu ?

Pour information, j'ai fait la semaine dernière une installation de vérification sur une vm vierge avec unbutu 18.04 LTS server, sans utiliser le mode cgi et sans rewrite (il ne sert pas en backoffice) cependant.

Pour la version de php j'ai utilisé le ppa:ondrej/php

**Comment by ohemelaar** [comment]
Bonjour,
J'utilisais Ubuntu 20.04 LTS serveur, je vais réessayer avec ces recommendations

**Comment by ohemelaar** [comment]
J'ai toujours la même erreur (`Undefined index: HTTP_X_REAL_IP in /home/ubuntu/console/tzr/local.php on line 17`).

**Comment by renaudzigmann** [comment]
Je réponds en l'absence de @xsalto-richard : cette variable est utilisée dans le cas où on se trouve derrière un proxy pour obtenir la vrai adresse IP. Cependant ce ne doit pas être une erreur bloquante. Je vais vérifier cela avec Richard. Est ce que vous avez d'autres messages ?

**Comment by ohemelaar** [comment]
Merci. Et non je n'ai pas d'autre message, la requête renvoie une 500 juste

**Comment by xsalto-richard** [comment]
Bonjour
vous avez le fichier logs/error.log avec l'erreur php sans doute ?
merci d'avance

**Comment by ohemelaar** [comment]
Voici les logs, le répertoire d'installation renseigné lors du lancement du script était `ubuntu/console` :
```
$ pwd 
/home/ubuntu
$ cat console/logs/error_log
[Fri Nov 25 10:58:01.543453 2022] [php7:notice] [pid 22465] [client ::1:56712] PHP Notice:  Undefined index: HTTP_X_REAL_IP in /home/ubuntu/console/tzr/local.php on line 17
[Fri Nov 25 10:58:03.399651 2022] [php7:notice] [pid 22466] [client ::1:56716] PHP Notice:  Undefined index: HTTP_X_REAL_IP in /home/ubuntu/console/tzr/local.php on line 17
```

**Comment by xsalto-richard** [comment]
Pas d'erreur fatale php doc.
Est-ce que je peux avoir l'arboresence (tree -L 3 ?) et le fichier var/logs/console.[domaine de votre install] ?
Merci d'avance

**Comment by ohemelaar** [comment]
Voici l'arborescence, par contre comme vous pouvez le voir il n'y a pas de fichier dans `var/logs/`
```
~/console$ tree -L 3
.
├── logs
│   ├── access_log
│   └── error_log
├── tzr
│   ├── local.ini
│   └── local.php
├── var
│   ├── cache
│   ├── checkpoints
│   ├── logs
│   └── tmp
└── www
    ├── admin -> csx/admin/
    ├── csx -> /home/ubuntu/csx
    ├── data
    │   └── TEMPLATES
    ├── index.php -> csx/scripts/index.php
    ├── json.php -> csx/scripts/json.php
    ├── scripts -> csx/scripts/
    └── templates_c

14 directories, 6 files
```
Merci à vous pour l'aide :pray:

**Comment by xsalto-richard** [comment]
Bonjour,
quand le fichier console.'ndd'.log n'est pas créé cela peut provenir de mauvais droits, ce serait supprenant ou de ...
vous avec les fichiers logs/error.log et logs/access.log ?
Merci d'avance.

**Comment by ohemelaar** [comment]
```
$ cat logs/access_log 
combinedproxy
combinedproxy
$ cat logs/error_log 
[Fri Nov 25 10:58:01.543453 2022] [php7:notice] [pid 22465] [client ::1:56712] PHP Notice:  Undefined index: HTTP_X_REAL_IP in /home/ubuntu/console/tzr/local.php on line 17
[Fri Nov 25 10:58:03.399651 2022] [php7:notice] [pid 22466] [client ::1:56716] PHP Notice:  Undefined index: HTTP_X_REAL_IP in /home/ubuntu/console/tzr/local.php on line 17
```

**Comment by xsalto-richard** [comment]
Bonjour,
Est-ce que les droits sont sur les dossiers sont ok ? 
PHP (le cgi ou le user apache si module) doit pouvoir écrire dans les dossiers www/data, www/templates_c (champs fichiers), dans le répertoire var (/logs, ...).

**Comment by xsalto-richard** [comment]
Bonjour,
est-ce que l'erreur 500 était due à des problèmes de droits sur les dossiers cités dessus ?

**Comment by ohemelaar** [comment]
Bonjour,
Je n'ai pas encore eu le temps de vérifier les permissions 😕 Je devrais pouvoir faire des essais demain, je vous tiens au courant !

**Comment by xsalto-richard** [comment]
bonjour
www/../var (et sous dossiers) doivent  être accessibles en écriture ansi que www/data et www/templates_c.
pour accéder au back office, vous utilisez quelle url ? /admin/ ?
merci d'avance

**Comment by ohemelaar** [comment]
Bonjour,
J'ai relancé une installation de zéro, avec les droits d'écriture sur les les dossiers que vous avez mentionnés et j'ai maintenant accès au back-office admin
Merci encore pour votre aide !
